;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-delete-forward
        comint-delchar-or-maybe-eof
        cua-delete-region
        cua-paste
        sp--self-insert-command
        ))

(setq mc/cmds-to-run-once
      '(
        ))
